<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>a6be58571d0076506541ff0a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-11-01 15:39:20</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>log.py:894</categoryid><desyncid>a6be58571d0076506541ff0a</desyncid><systemconfig/><screenshot/><desyncdata>[tingyul] Exception thrown while loading an object in an inventory. &#13;&#10;Object: Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44 Owner:  (AssertionError: [Object Manager] [tingyul] Attempting to move an object Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44 that is not in this manager or not the same object Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44 in manager)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 118, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 371, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 599, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1620, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 752, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 667, in batch_spawn_during_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 836, in _spawn_next_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 872, in _spawn_requested_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 502, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2187, in create_sim_instance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 191, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 713, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 195, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 92, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 328, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 2707, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 839, in load_items&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 192, in _load_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 850, in _create_inventory_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 199, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 849, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 878, in _post_create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\game_object.py", line 1390, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2286, in load_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 2373, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory_item.py", line 1235, in load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 358, in add_from_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 375, in _insert_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory_storage.py", line 323, in insert&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory_storage.py", line 504, in _insert&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 704, in move_to_inventory&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\log.py", line 894, in assert_raise&#13;&#10;AssertionError: [Object Manager] [tingyul] Attempting to move an object Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44 that is not in this manager or not the same object Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44 in managerrtim=0&#13;&#10;Client Session Time: 25.38&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>a6be58571d0076506541ff0a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-11-01 15:39:20</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>sim_inventory_component.py:119</categoryid><desyncid>a6be58571d0076506541ff0a</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44, reason:ResetReason.BEING_DESTROYED, stage:_Stage.DESTROY, being_processed:True, source:, cause:Inventory load failed. This will result in a partially reset object (AttributeError: 'NoneType' object has no attribute 'definition')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 118, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 371, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 599, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1620, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 752, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 667, in batch_spawn_during_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 836, in _spawn_next_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 872, in _spawn_requested_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 502, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2187, in create_sim_instance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 191, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 713, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 195, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 92, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 328, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 2707, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 839, in load_items&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 192, in _load_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 850, in _create_inventory_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 199, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 849, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 881, in _post_create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\script_object.py", line 880, in destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 431, in destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 293, in trigger_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 308, in trigger_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 453, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 119, in try_remove_object_by_id&#13;&#10;AttributeError: 'NoneType' object has no attribute 'definition'rtim=0&#13;&#10;Client Session Time: 25.38&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>a6be58571d0076506541ff0a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-11-01 15:39:20</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>indexed_manager.py:179</categoryid><desyncid>a6be58571d0076506541ff0a</desyncid><systemconfig/><screenshot/><desyncdata>Error during inventory load (ObjectIDError: ID collision detected. ID:704832821781728083, New Object:celebuSerum_Happy:0x09c811b790560b53, Existing Object:celebuSerum_Happy:0x09c811b790560b53)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 118, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 114, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 371, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 599, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1620, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 752, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 667, in batch_spawn_during_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 836, in _spawn_next_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner_service.py", line 872, in _spawn_requested_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_spawner.py", line 502, in spawn_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2187, in create_sim_instance&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 191, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 713, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 195, in add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 92, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 328, in call_on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 2707, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 839, in load_items&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 192, in _load_item&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\inventory.py", line 850, in _create_inventory_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\system.py", line 206, in create_object&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 179, in add&#13;&#10;indexed_manager.ObjectIDError: ID collision detected. ID:704832821781728083, New Object:celebuSerum_Happy:0x09c811b790560b53, Existing Object:celebuSerum_Happy:0x09c811b790560b53rtim=0&#13;&#10;Client Session Time: 25.38&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>a6be58571d0076506541ff0a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-11-01 15:39:44</createtime><buildsignature>Local.Unknown.Unknown.1.99.264.1030-1.200.000.600.Release</buildsignature><categoryid>sim_inventory_component.py:119</categoryid><desyncid>a6be58571d0076506541ff0a</desyncid><systemconfig/><screenshot/><desyncdata>[sscholl] Exception processing ResetRecord:&lt;Object_VacuumCleaner_Upright_High:0x0c6811b4a6a31d44, reason:ResetReason.BEING_DESTROYED, stage:_Stage.DESTROY, being_processed:True, source:None, cause:None. This will result in a partially reset object (AttributeError: 'NoneType' object has no attribute 'definition')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 207, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 221, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\persistence_service.py", line 418, in call_save_game_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 450, in request_client_disconnect_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 799, in on_teardown&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 332, in trigger_batch_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 325, in trigger_batch_reset&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 426, in start_processing&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 450, in _process&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\reset_and_delete_service.py", line 601, in _process_one_record&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\base_object.py", line 395, in on_reset_destroy&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 453, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\sim_inventory_component.py", line 119, in try_remove_object_by_id&#13;&#10;AttributeError: 'NoneType' object has no attribute 'definition'rtim=0&#13;&#10;Client Session Time: 25.38&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: hòB&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1060 3GB nvldumdx.dll 31.0.15.3758, GUID: D7B71E3E-5F42-11CF-5D7D-B3A50EC2D235&#13; &#10;</desyncdata></report>
</root>